[package]
name = "aoc"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[profile.release]
lto = true
panic = 'abort'

[dependencies]
libc = "*"
lazy_static = "*"
md5 = "0.2.1"
