[package]
name = "aoc"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[profile.release]
lto = true
panic = 'abort'

[dependencies]
libc = "*"
lazy_static = "*"
itertools = "*"
smallvec = "0.3.1"
image = "0.10.3"
base64 = "0.2.1"
